In [1]:
from sklearn.linear_model import LinearRegression
from itertools import product
import pandas as pd
import numpy as np
import matplotlib.style
import matplotlib.pyplot as plt

pd.options.display.float_format = '{:.8f}resam'.format
plt.style.use("seaborn-v0_8")
from itertools import product

In [2]:
df = pd.read_csv('eurusd_minute.csv', usecols=['Date', 'Time', 'BC'])
df['Datetime'] = df['Date'] + ' ' + df['Time']
df['Datetime'] = pd.to_datetime(df['Datetime'])
df = df.drop(['Date', 'Time'], axis=1)
df = df.set_index('Datetime')
df.rename(columns={"BC": "price"}, inplace=True)
df

,BO,BH,BL,price,BCh,AO,AH,AL,AC,ACh
Datetime,,,,,,,,,,
2005-01-02 18:29:00,1.35550000resam,1.35550000resam,1.35550000resam,1.35550000resam,0.00000000resam,1.35650000resam,1.35650000resam,1.35650000resam,1.35650000resam,0.00000000resam
2005-01-02 18:38:00,1.35550000resam,1.35550000resam,1.35550000resam,1.35550000resam,0.00000000resam,1.35650000resam,1.35650000resam,1.35650000resam,1.35650000resam,0.00000000resam
2005-01-02 18:51:00,1.35620000resam,1.35620000resam,1.35620000resam,1.35620000resam,0.00000000resam,1.35720000resam,1.35720000resam,1.35720000resam,1.35720000resam,0.00000000resam
2005-01-02 18:52:00,1.35600000resam,1.35600000resam,1.35600000resam,1.35600000resam,0.00000000resam,1.35700000resam,1.35700000resam,1.35700000resam,1.35700000resam,0.00000000resam
2005-01-02 18:55:00,1.35630000resam,1.35630000resam,1.35630000resam,1.35630000resam,0.00000000resam,1.35730000resam,1.35730000resam,1.35730000resam,1.35730000resam,0.00000000resam
...,...,...,...,...,...,...,...,...,...,...
2020-04-29 23:55:00,1.08770000resam,1.08770000resam,1.08763000resam,1.08764000resam,0.00006000resam,1.08784000resam,1.08784000resam,1.08776000resam,1.08778000resam,0.00006000resam
2020-04-29 23:56:00,1.08762000resam,1.08762000resam,1.08756000resam,1.08757000resam,0.00005000resam,1.08777000resam,1.08777000resam,1.08770000resam,1.08772000resam,0.00005000resam
2020-04-29 23:57:00,1.08759000resam,1.08761000resam,1.08757000resam,1.08759000resam,0.00000000resam,1.08774000resam,1.08775000resam,1.08773000resam,1.08773000resam,0.00001000resam
2020-04-29 23:58:00,1.08758000resam,1.08760000resam,1.08757000resam,1.08760000resam,-0.00002000resam,1.08772000resam,1.08775000resam,1.08771000resam,1.08775000resam,-0.00003000resam
2020-04-29 23:59:00,1.08761000resam,1.08768000resam,1.08761000resam,1.08767000resam,-0.00006000resam,1.08778000resam,1.08785000resam,1.08778000resam,1.08781000resam,-0.00003000resam

In [3]:
df = df.resample('10min').mean()
df.price = df.price.ffill()
df

,BO,BH,BL,price,BCh,AO,AH,AL,AC,ACh
Datetime,,,,,,,,,,
2005-01-02 18:20:00,1.35550000resam,1.35550000resam,1.35550000resam,1.35550000resam,0.00000000resam,1.35650000resam,1.35650000resam,1.35650000resam,1.35650000resam,0.00000000resam
2005-01-02 18:30:00,1.35550000resam,1.35550000resam,1.35550000resam,1.35550000resam,0.00000000resam,1.35650000resam,1.35650000resam,1.35650000resam,1.35650000resam,0.00000000resam
2005-01-02 18:40:00,NaN,NaN,NaN,1.35550000resam,NaN,NaN,NaN,NaN,NaN,NaN
2005-01-02 18:50:00,1.35617500resam,1.35617500resam,1.35617500resam,1.35617500resam,0.00000000resam,1.35717500resam,1.35717500resam,1.35717500resam,1.35717500resam,0.00000000resam
2005-01-02 19:00:00,1.35645000resam,1.35645000resam,1.35640000resam,1.35640000resam,0.00005000resam,1.35745000resam,1.35745000resam,1.35740000resam,1.35740000resam,0.00005000resam
...,...,...,...,...,...,...,...,...,...,...
2020-04-29 23:10:00,1.08737300resam,1.08739800resam,1.08735600resam,1.08737500resam,-0.00000200resam,1.08753700resam,1.08755400resam,1.08751700resam,1.08753400resam,0.00000300resam
2020-04-29 23:20:00,1.08749200resam,1.08752000resam,1.08747600resam,1.08749000resam,0.00000200resam,1.08765000resam,1.08767500resam,1.08763400resam,1.08765000resam,-0.00000000resam
2020-04-29 23:30:00,1.08761889resam,1.08765667resam,1.08759667resam,1.08763667resam,-0.00001778resam,1.08777333resam,1.08781222resam,1.08775333resam,1.08779333resam,-0.00002000resam
2020-04-29 23:40:00,1.08774000resam,1.08775600resam,1.08772500resam,1.08774300resam,-0.00000300resam,1.08788900resam,1.08790400resam,1.08787500resam,1.08788800resam,0.00000100resam
2020-04-29 23:50:00,1.08767111resam,1.08769000resam,1.08764444resam,1.08766333resam,0.00000778resam,1.08781889resam,1.08783444resam,1.08779111resam,1.08780556resam,0.00001333resam

In [4]:
df['returns'] = np.log(df['price'].div(df['price'].shift(1)))
df['direction'] = np.sign(df.returns)
df.direction.value_counts()

direction
1.00000000resam     289257
-1.00000000resam    287437
0.00000000resam     229163
Name: count, dtype: int64

In [5]:
lags = 5

cols = []
for lag in range(1, lags+1):
    col = "lag{}".format(lag)
    df[col] = df.returns.shift(lag)
    cols.append(col)
df.dropna(inplace=True)
df

,BO,BH,BL,price,BCh,AO,AH,AL,AC,ACh,returns,direction,lag1,lag2,lag3,lag4,lag5
Datetime,,,,,,,,,,,,,,,,,
2005-01-02 19:20:00,1.35555000resam,1.35573333resam,1.35546667resam,1.35561667resam,-0.00006667resam,1.35655000resam,1.35673333resam,1.35646667resam,1.35661667resam,-0.00006667resam,-0.00044865resam,-1.00000000resam,-0.00012903resam,0.00016589resam,0.00049785resam,0.00000000resam,0.00000000resam
2005-01-02 19:30:00,1.35546667resam,1.35546667resam,1.35523333resam,1.35523333resam,0.00023333resam,1.35646667resam,1.35646667resam,1.35623333resam,1.35623333resam,0.00023333resam,-0.00028281resam,-1.00000000resam,-0.00044865resam,-0.00012903resam,0.00016589resam,0.00049785resam,0.00000000resam
2005-01-02 19:40:00,1.35545000resam,1.35545000resam,1.35540000resam,1.35540000resam,0.00005000resam,1.35645000resam,1.35645000resam,1.35640000resam,1.35640000resam,0.00005000resam,0.00012297resam,1.00000000resam,-0.00028281resam,-0.00044865resam,-0.00012903resam,0.00016589resam,0.00049785resam
2005-01-02 19:50:00,1.35540000resam,1.35540000resam,1.35536667resam,1.35536667resam,0.00003333resam,1.35640000resam,1.35640000resam,1.35636667resam,1.35636667resam,0.00003333resam,-0.00002459resam,-1.00000000resam,0.00012297resam,-0.00028281resam,-0.00044865resam,-0.00012903resam,0.00016589resam
2005-01-02 20:00:00,1.35550000resam,1.35550000resam,1.35550000resam,1.35550000resam,0.00000000resam,1.35650000resam,1.35650000resam,1.35650000resam,1.35650000resam,0.00000000resam,0.00009837resam,1.00000000resam,-0.00002459resam,0.00012297resam,-0.00028281resam,-0.00044865resam,-0.00012903resam
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-04-29 23:10:00,1.08737300resam,1.08739800resam,1.08735600resam,1.08737500resam,-0.00000200resam,1.08753700resam,1.08755400resam,1.08751700resam,1.08753400resam,0.00000300resam,0.00002299resam,1.00000000resam,-0.00011219resam,-0.00000621resam,0.00005288resam,0.00002506resam,-0.00005518resam
2020-04-29 23:20:00,1.08749200resam,1.08752000resam,1.08747600resam,1.08749000resam,0.00000200resam,1.08765000resam,1.08767500resam,1.08763400resam,1.08765000resam,-0.00000000resam,0.00010575resam,1.00000000resam,0.00002299resam,-0.00011219resam,-0.00000621resam,0.00005288resam,0.00002506resam
2020-04-29 23:30:00,1.08761889resam,1.08765667resam,1.08759667resam,1.08763667resam,-0.00001778resam,1.08777333resam,1.08781222resam,1.08775333resam,1.08779333resam,-0.00002000resam,0.00013486resam,1.00000000resam,0.00010575resam,0.00002299resam,-0.00011219resam,-0.00000621resam,0.00005288resam
2020-04-29 23:40:00,1.08774000resam,1.08775600resam,1.08772500resam,1.08774300resam,-0.00000300resam,1.08788900resam,1.08790400resam,1.08787500resam,1.08788800resam,0.00000100resam,0.00009776resam,1.00000000resam,0.00013486resam,0.00010575resam,0.00002299resam,-0.00011219resam,-0.00000621resam
2020-04-29 23:50:00,1.08767111resam,1.08769000resam,1.08764444resam,1.08766333resam,0.00000778resam,1.08781889resam,1.08783444resam,1.08779111resam,1.08780556resam,0.00001333resam,-0.00007324resam,-1.00000000resam,0.00009776resam,0.00013486resam,0.00010575resam,0.00002299resam,-0.00011219resam